/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import entity.HoaDonChiTiet;
import java.io.File;
import java.io.FileOutputStream;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.NumberFormat;

import java.util.List;
import java.util.Locale;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;

import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import service.ServiceImpl.ThongKeServiceImpl;
import service.ThongKeService;

/**
 *
 * @author thong
 */
public class ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form ThongKe
     */
    private ThongKeServiceImpl tksi = new ThongKeService();
    DefaultTableModel model = new DefaultTableModel();
    private List<HoaDonChiTiet> chiTiets = tksi.getListTK();
    Locale locc = Locale.getDefault();
    NumberFormat nff = NumberFormat.getCurrencyInstance(locc);
    DecimalFormat formatter = new DecimalFormat("###,###,###");

    public ThongKe() {
        initComponents();
        loadTB();
//        DecimalFormat formatter = new DecimalFormat("###,###,###");
//        
////        BigDecimal dt = tksi.getListDoangThu();
        Locale loc = new Locale("nv", "VN");
        NumberFormat nf = NumberFormat.getCurrencyInstance(loc);
        lblDoangThu.setText(nf.format(tksi.getListDoangThu()));
        int hd = tksi.getListhoaDon();
        int kh = tksi.getLisKhachHang();
        lblHoaDon.setText(String.valueOf(hd));
        lblKhachHang.setText(String.valueOf(kh));

    }

    private void loadTB() {
        List<HoaDonChiTiet> chiTiets = tksi.getListTK();
        model = (DefaultTableModel) tblThongKe.getModel();
        model.setRowCount(0);
        for (HoaDonChiTiet x : chiTiets) {
            Object row[] = new Object[]{
                x.getTenSP(), x.getHoaDonBan(), x.getSoLuongBanRa(), formatter.format(x.getMaCTSPCT().getGiaNhap()), formatter.format(x.getMaCTSPCT().getGiaBan()), formatter.format(x.getTongTien())
            };
            model.addRow(row);
        }
    }

    private void loadTBDoanhThu() {
        List<HoaDonChiTiet> chiTiets = tksi.searchDoanhThu();
        model = (DefaultTableModel) tblThongKe.getModel();
        model.setRowCount(0);
        for (HoaDonChiTiet x : chiTiets) {
            Object row[] = new Object[]{
                x.getTenSP(), x.getHoaDonBan(), x.getSoLuongBanRa(), formatter.format(x.getMaCTSPCT().getGiaNhap()), formatter.format(x.getMaCTSPCT().getGiaBan()), formatter.format(x.getTongTien())
            };
            model.addRow(row);
        }
    }

    private void loadTBHoaDon() {
        List<HoaDonChiTiet> chiTiets = tksi.searchHoaDon();
        model = (DefaultTableModel) tblThongKe.getModel();
        model.setRowCount(0);
        for (HoaDonChiTiet x : chiTiets) {
            Object row[] = new Object[]{
                x.getTenSP(), x.getHoaDonBan(), x.getSoLuongBanRa(), formatter.format(x.getMaCTSPCT().getGiaNhap()), formatter.format(x.getMaCTSPCT().getGiaBan()), formatter.format(x.getTongTien())
            };
            model.addRow(row);
        }
    }

    private void loadTBSoLuong() {
        List<HoaDonChiTiet> chiTiets = tksi.searchSoLuong();
        model = (DefaultTableModel) tblThongKe.getModel();
        model.setRowCount(0);
        for (HoaDonChiTiet x : chiTiets) {
            Object row[] = new Object[]{
                x.getTenSP(), x.getHoaDonBan(), x.getSoLuongBanRa(), formatter.format(x.getMaCTSPCT().getGiaNhap()), formatter.format(x.getMaCTSPCT().getGiaBan()), formatter.format(x.getTongTien())
            };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblHoaDon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDoangThu = new javax.swing.JLabel();
        btnBaoCao = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtTensp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rboSoLuong = new javax.swing.JRadioButton();
        rboHoaDon = new javax.swing.JRadioButton();
        rboDoanhThu = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sản phẩm", "Số hóa đơn", "Số lượng", "Giá nhập", "Giá bán", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(tblThongKe);

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iImage/hoadon2.png"))); // NOI18N
        jLabel2.setText(" Hóa Đơn");

        lblHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoaDon.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iImage/KhachHang.png"))); // NOI18N
        jLabel3.setText(" Khách Hàng");

        lblKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhachHang.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(248, 169, 50));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText(" Xuất Thống kê");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iImage/Thongke2.png"))); // NOI18N
        jLabel1.setText("Doanh Thu");

        lblDoangThu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDoangThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoangThu.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDoangThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDoangThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnBaoCao.setBackground(new java.awt.Color(248, 169, 50));
        btnBaoCao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBaoCao.setText("Gửi Báo Cáo");
        btnBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoCaoActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtTensp.setText("@");
        txtTensp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenspKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tên sản phẩm:");

        buttonGroup1.add(rboSoLuong);
        rboSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rboSoLuong.setText("Số lượng");
        rboSoLuong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rboSoLuongItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rboHoaDon);
        rboHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rboHoaDon.setText("Hóa đơn");
        rboHoaDon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rboHoaDonItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rboDoanhThu);
        rboDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rboDoanhThu.setText("Doanh thu");
        rboDoanhThu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rboDoanhThuItemStateChanged(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(248, 169, 50));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Biểu đồ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(rboSoLuong)
                .addGap(89, 89, 89)
                .addComponent(rboHoaDon)
                .addGap(96, 96, 96)
                .addComponent(rboDoanhThu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(rboSoLuong)
                    .addComponent(rboHoaDon)
                    .addComponent(rboDoanhThu))
                .addGap(21, 21, 21))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(141, 141, 141)
                .addComponent(btnBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(394, 394, 394))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BieuDo bd = new BieuDo();
        bd.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaoCaoActionPerformed
        // TODO add your handling code here:

        Properties p = new Properties();
        p.put("mail.smtp.auth", "true");
        p.put("mail.smtp.starttls.enable", "true");
        p.put("mail.smtp.starttls.requied", "true");
        p.put("mail.smtp.ssl.trust", "smtp.gmail.com");
        p.put("mail.smtp.ssl.protocols", "TLSv1.2");
        p.put("mail.smtp.host", "smtp.gmail.com");
        p.put("mail.smtp.port", 587);

        String accountName = "thongbt8@gmail.com";
        String accountPassword = "nygldtheqtlksmrm";
        Session s = Session.getInstance(p, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(accountName, accountPassword);
            }
        });
        String from = "thongbt8@gmail.com";
        String to = "iamanhne29@gmail.com";
        String subject = "Báo cáo thống kê";
        String body = "Doanh thu:" + lblDoangThu.getText() + "," + "Hóa đơn:" + lblHoaDon.getText() + "," + "Khách hàng:" + lblKhachHang.getText();
        try {
            Message msg = new MimeMessage(s);
            msg.setFrom(new InternetAddress(from));
            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
            msg.setSubject(subject);
            msg.setText(body);
            MimeBodyPart contenPart = new MimeBodyPart();
            contenPart.setContent(body, "text/html: charset=utf-8");

//
//            MimeBodyPart filepart = new MimeBodyPart();
//            File f = new File("D://DanhSach.xlsx");
//            FileDataSource source = new FileDataSource(f);
//            filepart.setDataHandler(new DataHandler(source));
//            filepart.setFileName(f.getName());
//            MimeMultipart mimeMultipart = new MimeMultipart();
//            mimeMultipart.addBodyPart(contenPart);
//            mimeMultipart.addBodyPart(filepart);
//            
//            msg.setContent(mimeMultipart);
            Transport.send(msg);
            JOptionPane.showMessageDialog(this, "Gửi mail thành công");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnBaoCaoActionPerformed

    private void rboSoLuongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rboSoLuongItemStateChanged
        // TODO add your handling code here:
        loadTBSoLuong();
    }//GEN-LAST:event_rboSoLuongItemStateChanged

    private void rboHoaDonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rboHoaDonItemStateChanged
        // TODO add your handling code here
        loadTBHoaDon();
    }//GEN-LAST:event_rboHoaDonItemStateChanged

    private void rboDoanhThuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rboDoanhThuItemStateChanged
        // TODO add your handling code here:
        loadTBDoanhThu();
    }//GEN-LAST:event_rboDoanhThuItemStateChanged

    private void txtTenspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenspKeyReleased
        // TODO add your handling code here:
        if (txtTensp.getText().length() == 0) {
            loadTB();
        } else {
            List<HoaDonChiTiet> chiTiets = tksi.searchTenSP(txtTensp.getText());
            model = (DefaultTableModel) tblThongKe.getModel();
            model.setRowCount(0);
            for (HoaDonChiTiet x : chiTiets) {
                Object row[] = new Object[]{
                    x.getTenSP(), x.getHoaDonBan(), x.getSoLuongBanRa(), formatter.format(x.getMaCTSPCT().getGiaNhap()), formatter.format(x.getMaCTSPCT().getGiaBan()), formatter.format(x.getTongTien())
                };
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_txtTenspKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet fSheet = workbook.createSheet("danhsach");
            XSSFRow row = null;
            Cell cell = null;
            row = fSheet.createRow(1);//tao dong trong ben tren

            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Sản phẩm");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Số hóa đơn");

            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Số lượng");

            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Giá nhập");

            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Giá bán");

            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("Tổng tiền");

            for (int i = 0; i < chiTiets.size(); i++) {
                row = fSheet.createRow(2 + i);

                cell = row.createCell(0, CellType.NUMERIC);
                cell.setCellValue(i + 1);

                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(chiTiets.get(i).getTenSP());

                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(chiTiets.get(i).getHoaDonBan());

                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue(chiTiets.get(i).getSoLuongBanRa());

                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue(chiTiets.get(i).getMaCTSPCT().getGiaNhap());

                cell = row.createCell(5, CellType.STRING);
                cell.setCellValue(chiTiets.get(i).getMaCTSPCT().getGiaBan());

                cell = row.createCell(6, CellType.STRING);
                cell.setCellValue(chiTiets.get(i).getTongTien());
            }
            File f = new File("D://DanhSach.xlsx");
            try {
                FileOutputStream stream = new FileOutputStream(f);
                workbook.write(stream);
                stream.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Xuất thành công");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaoCao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDoangThu;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JRadioButton rboDoanhThu;
    private javax.swing.JRadioButton rboHoaDon;
    private javax.swing.JRadioButton rboSoLuong;
    private javax.swing.JTable tblThongKe;
    private javax.swing.JTextField txtTensp;
    // End of variables declaration//GEN-END:variables
}
